server:
  port: 8081
  servlet:
    context-path: /oauth
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    validation-query: SELECT 1
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/security2?useUnicode=true&characterEncoding=utf-8
  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 200ms
    lettuce:
      pool:
        max-active: 100 #最大连接数
        max-idle: 20 #最大空闲链接
        min-idle: 10 #最小空闲链接
        time-between-eviction-runs: 2000ms # 每2秒回收一次
  #不加这个,swagger 会报错
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher